### ISSUE TITLE
Multiple Definitions Problem

### ISSUE THREAD

**Issue by fragwuerdig** [mbientlab/MetaWear-SDK-Cpp#17]
Hello mbientlab,

there are various occasions of constants that are being declared AND defined inside headers that can externally be included by projects. Examples are the MBL_MW_STATUS constants in core/status.h.

 If two separate source files of a project using the metawear API include the same header (e.g. status.h) then these constants are getting redefined, which is not supported by the GNU compiler collection. This problem can not be guarded by the #prage once statement as it only prevents recursive inclusion of headers.

Please, provide information on how to workaround this problem.

Best,
Till

**Comment by fragwuerdig** [comment]
Is and C++ vs. C issue and not metawear related - sorry for having spammed the issues table.
Best,
Till

**Comment by scaryghost** [comment]
Yes, const is treated differently in C vs C++.  Since the library does present itself with a C style interface, the header files should be updated to use ``#define`` instead of ``const`` if ``__cplusplus`` is not defined, which will fix this issue.
