### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by mikewilt** [mbientlab/MetaWear-SDK-Cpp#20]
I am getting this trying to build the latest using g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
It goes smoothly until this command.

g++ -MMD -MP -MF "build/x64/release/src/metawear/dfu/cpp/miniz.d" -c -o build/x64/release/src/metawear/dfu/cpp/miniz.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS  -O3 -m64 src/metawear/dfu/cpp/miniz.cpp
src/metawear/dfu/cpp/miniz.cpp: In function ‘void tdefl_find_match(tdefl_compressor*, mz_uint, mz_uint, mz_uint, mz_uint*, mz_uint*)’:
src/metawear/dfu/cpp/miniz.cpp:1356:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 #define TDEFL_READ_UNALIGNED_WORD(p) *(const mz_uint16 *)(p)
                                                            ^
src/metawear/dfu/cpp/miniz.cpp:1364:21: note: in expansion of macro ‘TDEFL_READ_UNALIGNED_WORD’
     mz_uint16 c01 = TDEFL_READ_UNALIGNED_WORD(&d->m_dict[pos + match_len - 1]), s01 = TDEFL_READ_UNALIGNED_WORD2(s);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1356:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 #define TDEFL_READ_UNALIGNED_WORD(p) *(const mz_uint16 *)(p)
                                                            ^
src/metawear/dfu/cpp/miniz.cpp:1379:9: note: in expansion of macro ‘TDEFL_READ_UNALIGNED_WORD’
     if (TDEFL_READ_UNALIGNED_WORD(&d->m_dict[probe_pos + match_len - 1]) == c01)                \
         ^~~~~~~~~~~~~~~~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1381:13: note: in expansion of macro ‘TDEFL_PROBE’
             TDEFL_PROBE;
             ^~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1356:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 #define TDEFL_READ_UNALIGNED_WORD(p) *(const mz_uint16 *)(p)
                                                            ^
src/metawear/dfu/cpp/miniz.cpp:1379:9: note: in expansion of macro ‘TDEFL_READ_UNALIGNED_WORD’
     if (TDEFL_READ_UNALIGNED_WORD(&d->m_dict[probe_pos + match_len - 1]) == c01)                \
         ^~~~~~~~~~~~~~~~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1382:13: note: in expansion of macro ‘TDEFL_PROBE’
             TDEFL_PROBE;
             ^~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1356:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 #define TDEFL_READ_UNALIGNED_WORD(p) *(const mz_uint16 *)(p)
                                                            ^
src/metawear/dfu/cpp/miniz.cpp:1379:9: note: in expansion of macro ‘TDEFL_READ_UNALIGNED_WORD’
     if (TDEFL_READ_UNALIGNED_WORD(&d->m_dict[probe_pos + match_len - 1]) == c01)                \
         ^~~~~~~~~~~~~~~~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1383:13: note: in expansion of macro ‘TDEFL_PROBE’
             TDEFL_PROBE;
             ^~~~~~~~~~~
src/metawear/dfu/cpp/miniz.cpp:1356:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 #define TDEFL_READ_UNALIGNED_WORD(p) *(const mz_uint16 *)(p)
                                                            ^
src/metawear/dfu/cpp/miniz.cpp:1407:19: note: in expansion of macro ‘TDEFL_READ_UNALIGNED_WORD’
             c01 = TDEFL_READ_UNALIGNED_WORD(&d->m_dict[pos + match_len - 1]);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/metawear/dfu/cpp/miniz.cpp:27:0:
src/metawear/dfu/cpp/miniz.cpp: In function ‘mz_bool mz_zip_validate_file(mz_zip_archive*, mz_uint, mz_uint)’:
src/metawear/dfu/cpp/miniz.h:531:49: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 #define MZ_READ_LE32(p) *((const mz_uint32 *)(p))
                                                 ^
src/metawear/dfu/cpp/miniz.cpp:5249:19: note: in expansion of macro ‘MZ_READ_LE32’
         has_id = (MZ_READ_LE32(descriptor_buf) == MZ_ZIP_DATA_DESCRIPTOR_ID);
                   ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Makefile:65: recipe for target 'build/x64/release/src/metawear/dfu/cpp/miniz.o' failed
make: *** [build/x64/release/src/metawear/dfu/cpp/miniz.o] Error 1

**Comment by scaryghost** [comment]
make OPT_FLAGS=-Wno-strict-aliasing
