### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by antelbra** [mbientlab/MetaWear-SDK-Cpp#21]
Hi, I'm getting this error in macOS Mojave (clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-apple-darwin18.2.0). The same error with "-Wno-strict-aliasing" flag:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2285:5: error: 
      delete called on non-final 'DfuOperations' that has virtual functions but
      non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    delete __ptr;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2598:7: note: 
      in instantiation of member function
      'std::__1::default_delete<DfuOperations>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
src/metawear/impl/cpp/metawearboard.cpp:850:23: note: in instantiation of member
      function 'std::__1::unique_ptr<DfuOperations,
      std::__1::default_delete<DfuOperations> >::reset' requested here
    board->operations.reset(new DfuOperations(board, delegate));
                      ^
1 error generated.
make: *** [build/x64/release/src/metawear/impl/cpp/metawearboard.o] Error 1

**Comment by scaryghost** [comment]
Thanks for the report; this should be a quick fix.

**Comment by antelbra** [comment]
Thank you for the quick reply ✌️
