### ISSUE TITLE
Build Error: C2593: 'operator =' is ambiguous

### ISSUE THREAD

**Issue by Crigges** [mbientlab/MetaWear-SDK-Cpp#24]
Hello,
I use VS2019, therefore I upgraded to:
PlatformToolset: v142
WindowsTargetPlatformVersion: 10.0.17763.0

When building I get the following two Errors:
```
"\MetaWear-SDK-Cpp-0.18.4\MetaWear.Win32.vcxproj" (default target) (1) ->
(ClCompile target) ->
  \MetaWear-SDK-Cpp-0.18.4\src\metawear\dfu\cpp\file_operations.cpp(127,48): error C2593: 'operator =' is ambiguous [\MetaWea
r-SDK-Cpp-0.18.4\MetaWear.Win32.vcxproj]
  \MetaWear-SDK-Cpp-0.18.4\src\metawear\dfu\cpp\file_operations.cpp(131,48): error C2593: 'operator =' is ambiguous [\MetaWea
r-SDK-Cpp-0.18.4\MetaWear.Win32.vcxproj]
```

Full Output: https://pastebin.com/SCA8NG9e

The build works fine when fixing those two lines.

**Comment by hectorC** [comment]
> 
> The build works fine when fixing those two lines.

Would you mind sharing the fix? I'm running into the same issue but haven't been able to figure out the solution.

**Comment by hectorC** [comment]
This seems to fix the error, hopefully it is the right thing to do:
firmwareFilename = it2.value().get<std::string>();

**Comment by RascoApps** [comment]
Thanks, I’ll give that I try, I just ran into error as well

**Comment by lkasso** [comment]
Closing as we are not longer supporting Windows.

**Comment by hectorC** [comment]
Why is that you are not supporting Windows anymore? I just built an application for Windows that works great and would generate sales for your trackers to a possibly large number of users.
